---
spring:
  profiles: peer1
  application: 
    name: api_gateway
server:
  port: 8085

eureka:
  client:
    enabled: false
  
zuul:
  routes:
    ws_user:
      url: http://localhost:8080/
      path: /ws_user/**
      
ribbon:
  eureka:
    enabled: ${eureka.client.enabled}      