---
spring:
  profiles: default
  application: 
    name: api_gateway
server:
  port: 8085

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED}


ribbon:
  eureka:
    enabled: ${eureka.client.enabled}    
  
zuul:
  routes:
    ws_user:
      url: http://localhost:8080/
      path: /ws_user/**

      